<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZrc6qle\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZrc6qle/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZrc6qle.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZrc6qle\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZrc6qle\appDevDebugProjectContainer([
    'container.build_hash' => 'Zrc6qle',
    'container.build_id' => '581a38a4',
    'container.build_time' => 1744148397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZrc6qle');
