<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'klaviyops.klaviyo_service.customer_event_service' shared service.

return $this->services['klaviyops.klaviyo_service.customer_event_service'] = new \KlaviyoPs\Classes\KlaviyoServices\CustomerEventService(${($_ = isset($this->services['klaviyops.prestashop_services.datetime']) ? $this->services['klaviyops.prestashop_services.datetime'] : ($this->services['klaviyops.prestashop_services.datetime'] = new \KlaviyoPs\Classes\PrestashopServices\DateTimeService())) && false ?: '_'}, ${($_ = isset($this->services['klaviyops.prestashop_services.context']) ? $this->services['klaviyops.prestashop_services.context'] : $this->load('getKlaviyops_PrestashopServices_ContextService.php')) && false ?: '_'}, ${($_ = isset($this->services['klaviyops.prestashop_services.customer']) ? $this->services['klaviyops.prestashop_services.customer'] : $this->load('getKlaviyops_PrestashopServices_CustomerService.php')) && false ?: '_'});
