<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'klaviyops.prestashop_services.customer' shared service.

return $this->services['klaviyops.prestashop_services.customer'] = new \KlaviyoPs\Classes\PrestashopServices\CustomerService(${($_ = isset($this->services['klaviyops.prestashop_services.validate']) ? $this->services['klaviyops.prestashop_services.validate'] : ($this->services['klaviyops.prestashop_services.validate'] = new \KlaviyoPs\Classes\PrestashopServices\ValidateService())) && false ?: '_'}, ${($_ = isset($this->services['klaviyops.prestashop_services.datetime']) ? $this->services['klaviyops.prestashop_services.datetime'] : ($this->services['klaviyops.prestashop_services.datetime'] = new \KlaviyoPs\Classes\PrestashopServices\DateTimeService())) && false ?: '_'}, ${($_ = isset($this->services['klaviyops.prestashop_services.context']) ? $this->services['klaviyops.prestashop_services.context'] : $this->load('getKlaviyops_PrestashopServices_ContextService.php')) && false ?: '_'});
