<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTvt5dbq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTvt5dbq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTvt5dbq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTvt5dbq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTvt5dbq\appProdProjectContainer([
    'container.build_hash' => 'Tvt5dbq',
    'container.build_id' => '1f9cb716',
    'container.build_time' => 1744153664,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTvt5dbq');
